---
- name: Install oh-my-zsh, powerlevel9k theme, fzf, autosuggestions, syntax-highlighting
  hosts: all
  vars_files:
    - vars/main.yml
  become: true
  gather_facts: no # don't gather facts because /usr/bin/python isn't set
  roles:
    - pre-tasks
    - zsh
    - oh_my_zsh
